In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import pickle

In [2]:
# Read the csv file
data_df = pd.read_csv('Churn_Modelling.csv')
data_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
## Estimated Salary will be the O/P feature, rest are input feature
# Drop unnecessary columns
data_df = data_df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# Encode categorical variables
le_gender = LabelEncoder()
data_df['Gender'] = le_gender.fit_transform(data_df['Gender'])
data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
# One-hot encode 'Geography' column
# This is being done to since 'Geography' has more than two categories

from sklearn.preprocessing import OneHotEncoder
ohe_geography = OneHotEncoder(drop='first', sparse_output=False)
geography_encoded = ohe_geography.fit_transform(data_df[['Geography']])
geo_encoded_df = pd.DataFrame(geography_encoded, columns=ohe_geography.get_feature_names_out())
geo_encoded_df

      Geography_Germany  Geography_Spain
0                   0.0              0.0
1                   0.0              1.0
2                   0.0              0.0
3                   0.0              0.0
4                   0.0              1.0
...                 ...              ...
9995                0.0              0.0
9996                0.0              0.0
9997                0.0              0.0
9998                1.0              0.0
9999                0.0              0.0

[10000 rows x 2 columns]

In [8]:
# Combine the encoded geography columns back to the main dataframe
data_df = pd.concat([data_df.drop('Geography', axis=1), geo_encoded_df], axis=1)
data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,0.0,0.0

In [9]:
# Divide the dataset into features and target variable
X = data_df.drop('EstimatedSalary', axis=1) # Features
y = data_df['EstimatedSalary'] # Target variable

In [12]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
# Save the encoders for future use
with open('le_gender.pkl', 'wb') as f:
    pickle.dump(le_gender, f)

with open('ohe_geography.pkl', 'wb') as f:
    pickle.dump(ohe_geography, f)

ANN Regression Problem

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [16]:
# Build the ANN model
model = Sequential(Dense(units=64, activation='relu', input_shape=(X_train.shape[1],))) ## Hidden Layer 1 Connected with input layer
model.add(Dense(units=32, activation='relu'))  ## Hidden Layer 2
model.add(Dense(units=1))  ## Output Layer

In [17]:
# Compile the model. These parameters are suitable for regression tasks
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                768

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2881 (11.25 KB)
Trainable params: 2881 (11.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Set up the TensorBoard callback
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%  H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [19]:
# Setup Early Stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [20]:
# Train the model
history = model.fit(X_train, y_train, validation_split=0.2, epochs=100, batch_size=32,
                    callbacks=[early_stopping, tensorboard_callback])

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test Accuracy: {test_accuracy}')

Epoch 1/100
200/200 [==============================] - 0s 884us/step - loss: 99974.6406 - mae: 99974.6406 - val_loss: 102016.8438 - val_mae: 102016.8438
Epoch 2/100
200/200 [==============================] - 0s 525us/step - loss: 99550.4219 - mae: 99550.4219 - val_loss: 101149.4766 - val_mae: 101149.4766
Epoch 3/100
200/200 [==============================] - 0s 504us/step - loss: 97997.5078 - mae: 97997.5078 - val_loss: 98831.5391 - val_mae: 98831.5391
Epoch 4/100
200/200 [==============================] - 0s 515us/step - loss: 94785.8516 - mae: 94785.8516 - val_loss: 94711.1719 - val_mae: 94711.1719
Epoch 5/100
200/200 [==============================] - 0s 523us/step - loss: 89810.2891 - mae: 89810.2891 - val_loss: 88834.2500 - val_mae: 88834.2500
Epoch 6/100
200/200 [==============================] - 0s 518us/step - loss: 83360.4453 - mae: 83360.4453 - val_loss: 81568.4688 - val_mae: 81568.4688
Epoch 7/100
200/200 [==============================] - 0s 509us/step - loss: 75968.0078 - mae: 75968.0078 - val_loss: 73810.5469 - val_mae: 73810.5469
Epoch 8/100
200/200 [==============================] - 0s 514us/step - loss: 68729.9531 - mae: 68729.9531 - val_loss: 66607.2188 - val_mae: 66607.2188
Epoch 9/100
200/200 [==============================] - 0s 537us/step - loss: 62465.5664 - mae: 62465.5664 - val_loss: 60665.0547 - val_mae: 60665.0547
Epoch 10/100
200/200 [==============================] - 0s 520us/step - loss: 57539.2891 - mae: 57539.2891 - val_loss: 56229.2656 - val_mae: 56229.2656
Epoch 11/100
200/200 [==============================] - 0s 517us/step - loss: 54251.5859 - mae: 54251.5859 - val_loss: 53459.4961 - val_mae: 53459.4961
Epoch 12/100
200/200 [==============================] - 0s 526us/step - loss: 52292.5469 - mae: 52292.5469 - val_loss: 51780.9102 - val_mae: 51780.9102
Epoch 13/100
200/200 [==============================] - 0s 504us/step - loss: 51256.4453 - mae: 51256.4453 - val_loss: 50880.7344 - val_mae: 50880.7344
Epoch 14/100
200/200 [==============================] - 0s 509us/step - loss: 50721.3203 - mae: 50721.3203 - val_loss: 50457.4258 - val_mae: 50457.4258
Epoch 15/100
200/200 [==============================] - 0s 755us/step - loss: 50446.0703 - mae: 50446.0703 - val_loss: 50223.5039 - val_mae: 50223.5039
Epoch 16/100
200/200 [==============================] - 0s 515us/step - loss: 50301.2891 - mae: 50301.2891 - val_loss: 50117.2852 - val_mae: 50117.2852
Epoch 17/100
200/200 [==============================] - 0s 522us/step - loss: 50206.0664 - mae: 50206.0664 - val_loss: 50038.4766 - val_mae: 50038.4766
Epoch 18/100
200/200 [==============================] - 0s 506us/step - loss: 50128.6055 - mae: 50128.6055 - val_loss: 49997.0742 - val_mae: 49997.0742
Epoch 19/100
200/200 [==============================] - 0s 502us/step - loss: 50073.0547 - mae: 50073.0547 - val_loss: 49973.6758 - val_mae: 49973.6758
Epoch 20/100
200/200 [==============================] - 0s 502us/step - loss: 50030.1562 - mae: 50030.1562 - val_loss: 49952.9297 - val_mae: 49952.9297
Epoch 21/100
200/200 [==============================] - 0s 504us/step - loss: 49995.3438 - mae: 49995.3438 - val_loss: 49944.9219 - val_mae: 49944.9219
Epoch 22/100
200/200 [==============================] - 0s 499us/step - loss: 49962.1133 - mae: 49962.1133 - val_loss: 49931.0898 - val_mae: 49931.0898
Epoch 23/100
200/200 [==============================] - 0s 501us/step - loss: 49936.3789 - mae: 49936.3789 - val_loss: 49919.1914 - val_mae: 49919.1914
Epoch 24/100
200/200 [==============================] - 0s 502us/step - loss: 49908.7305 - mae: 49908.7305 - val_loss: 49907.2383 - val_mae: 49907.2383
Epoch 25/100
200/200 [==============================] - 0s 502us/step - loss: 49887.8789 - mae: 49887.8789 - val_loss: 49896.3867 - val_mae: 49896.3867
Epoch 26/100
200/200 [==============================] - 0s 499us/step - loss: 49866.1914 - mae: 49866.1914 - val_loss: 49881.5000 - val_mae: 49881.5000
Epoch 27/100
200/200 [==============================] - 0s 502us/step - loss: 49848.6211 - mae: 49848.6211 - val_loss: 49874.2617 - val_mae: 49874.2617
Epoch 28/100
200/200 [==============================] - 0s 502us/step - loss: 49827.5312 - mae: 49827.5312 - val_loss: 49867.0859 - val_mae: 49867.0859
Epoch 29/100
200/200 [==============================] - 0s 499us/step - loss: 49812.0547 - mae: 49812.0547 - val_loss: 49855.5469 - val_mae: 49855.5469
Epoch 30/100
200/200 [==============================] - 0s 502us/step - loss: 49793.7148 - mae: 49793.7148 - val_loss: 49849.3945 - val_mae: 49849.3945
Epoch 31/100
200/200 [==============================] - 0s 500us/step - loss: 49778.4883 - mae: 49778.4883 - val_loss: 49837.5039 - val_mae: 49837.5039
Epoch 32/100
200/200 [==============================] - 0s 500us/step - loss: 49758.5117 - mae: 49758.5117 - val_loss: 49833.8203 - val_mae: 49833.8203
Epoch 33/100
200/200 [==============================] - 0s 503us/step - loss: 49744.0898 - mae: 49744.0898 - val_loss: 49826.6211 - val_mae: 49826.6211
Epoch 34/100
200/200 [==============================] - 0s 503us/step - loss: 49728.7266 - mae: 49728.7266 - val_loss: 49819.1094 - val_mae: 49819.1094
Epoch 35/100
200/200 [==============================] - 0s 502us/step - loss: 49719.9883 - mae: 49719.9883 - val_loss: 49814.5469 - val_mae: 49814.5469
Epoch 36/100
200/200 [==============================] - 0s 533us/step - loss: 49705.3555 - mae: 49705.3555 - val_loss: 49811.4531 - val_mae: 49811.4531
Epoch 37/100
200/200 [==============================] - 0s 499us/step - loss: 49691.6055 - mae: 49691.6055 - val_loss: 49805.2109 - val_mae: 49805.2109
Epoch 38/100
200/200 [==============================] - 0s 500us/step - loss: 49679.1211 - mae: 49679.1211 - val_loss: 49804.4219 - val_mae: 49804.4219
Epoch 39/100
200/200 [==============================] - 0s 502us/step - loss: 49667.4844 - mae: 49667.4844 - val_loss: 49800.6992 - val_mae: 49800.6992
Epoch 40/100
200/200 [==============================] - 0s 498us/step - loss: 49656.5742 - mae: 49656.5742 - val_loss: 49796.2656 - val_mae: 49796.2656
Epoch 41/100
200/200 [==============================] - 0s 494us/step - loss: 49645.6602 - mae: 49645.6602 - val_loss: 49788.9258 - val_mae: 49788.9258
Epoch 42/100
200/200 [==============================] - 0s 499us/step - loss: 49631.4531 - mae: 49631.4531 - val_loss: 49787.5938 - val_mae: 49787.5938
Epoch 43/100
200/200 [==============================] - 0s 502us/step - loss: 49621.2734 - mae: 49621.2734 - val_loss: 49789.0508 - val_mae: 49789.0508
Epoch 44/100
200/200 [==============================] - 0s 503us/step - loss: 49610.5117 - mae: 49610.5117 - val_loss: 49782.5234 - val_mae: 49782.5234
Epoch 45/100
200/200 [==============================] - 0s 501us/step - loss: 49602.4453 - mae: 49602.4453 - val_loss: 49781.5000 - val_mae: 49781.5000
Epoch 46/100
200/200 [==============================] - 0s 502us/step - loss: 49590.8008 - mae: 49590.8008 - val_loss: 49783.9219 - val_mae: 49783.9219
Epoch 47/100
200/200 [==============================] - 0s 504us/step - loss: 49581.9102 - mae: 49581.9102 - val_loss: 49778.9453 - val_mae: 49778.9453
Epoch 48/100
200/200 [==============================] - 0s 503us/step - loss: 49571.4609 - mae: 49571.4609 - val_loss: 49777.3984 - val_mae: 49777.3984
Epoch 49/100
200/200 [==============================] - 0s 499us/step - loss: 49566.2812 - mae: 49566.2812 - val_loss: 49776.8359 - val_mae: 49776.8359
Epoch 50/100
200/200 [==============================] - 0s 500us/step - loss: 49558.5195 - mae: 49558.5195 - val_loss: 49772.8203 - val_mae: 49772.8203
Epoch 51/100
200/200 [==============================] - 0s 492us/step - loss: 49549.7461 - mae: 49549.7461 - val_loss: 49772.8867 - val_mae: 49772.8867
Epoch 52/100
200/200 [==============================] - 0s 500us/step - loss: 49542.4336 - mae: 49542.4336 - val_loss: 49771.2852 - val_mae: 49771.2852
Epoch 53/100
200/200 [==============================] - 0s 500us/step - loss: 49537.0195 - mae: 49537.0195 - val_loss: 49771.9141 - val_mae: 49771.9141
Epoch 54/100
200/200 [==============================] - 0s 496us/step - loss: 49529.2148 - mae: 49529.2148 - val_loss: 49770.3281 - val_mae: 49770.3281
Epoch 55/100
200/200 [==============================] - 0s 498us/step - loss: 49518.9297 - mae: 49518.9297 - val_loss: 49767.9766 - val_mae: 49767.9766
Epoch 56/100
200/200 [==============================] - 0s 498us/step - loss: 49512.7891 - mae: 49512.7891 - val_loss: 49772.1289 - val_mae: 49772.1289
Epoch 57/100
200/200 [==============================] - 0s 499us/step - loss: 49504.7461 - mae: 49504.7461 - val_loss: 49766.5781 - val_mae: 49766.5781
Epoch 58/100
200/200 [==============================] - 0s 500us/step - loss: 49496.8359 - mae: 49496.8359 - val_loss: 49766.0312 - val_mae: 49766.0312
Epoch 59/100
200/200 [==============================] - 0s 500us/step - loss: 49490.7031 - mae: 49490.7031 - val_loss: 49764.8438 - val_mae: 49764.8438
Epoch 60/100
200/200 [==============================] - 0s 498us/step - loss: 49485.4336 - mae: 49485.4336 - val_loss: 49766.4258 - val_mae: 49766.4258
Epoch 61/100
200/200 [==============================] - 0s 503us/step - loss: 49478.9219 - mae: 49478.9219 - val_loss: 49763.7461 - val_mae: 49763.7461
Epoch 62/100
200/200 [==============================] - 0s 500us/step - loss: 49474.8516 - mae: 49474.8516 - val_loss: 49762.7383 - val_mae: 49762.7383
Epoch 63/100
200/200 [==============================] - 0s 500us/step - loss: 49466.1445 - mae: 49466.1445 - val_loss: 49764.9766 - val_mae: 49764.9766
Epoch 64/100
200/200 [==============================] - 0s 500us/step - loss: 49461.0195 - mae: 49461.0195 - val_loss: 49767.0352 - val_mae: 49767.0352
Epoch 65/100
200/200 [==============================] - 0s 500us/step - loss: 49454.3594 - mae: 49454.3594 - val_loss: 49764.8906 - val_mae: 49764.8906
Epoch 66/100
200/200 [==============================] - 0s 498us/step - loss: 49446.9453 - mae: 49446.9453 - val_loss: 49764.7383 - val_mae: 49764.7383
Epoch 67/100
200/200 [==============================] - 0s 505us/step - loss: 49442.9648 - mae: 49442.9648 - val_loss: 49768.7500 - val_mae: 49768.7500
63/63 [==============================] - 0s 299us/step - loss: 50354.9141 - mae: 50354.9141
Test Loss: 50354.9140625, Test Accuracy: 50354.9140625

In [21]:
# Evaluate the model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 [==============================] - 0s 298us/step - loss: 50354.9141 - mae: 50354.9141
Test Loss: 50354.9140625, Test MAE: 50354.9140625

In [22]:
#Save the trained model
model.save('salary_regression_model.h5')

/Users/satyakibasu/Documents/Satyaki/python_code/gen-ai/p311env/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(